### ISSUE TITLE
cc_embed_data.srcs should be listed as no-sort

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/buildtools#1004]
The order of elements in the sources impacts the order of embedded data, so we should respect the user order.

**Comment by aiuto** [comment]
I am changing my mind on this. The problem is more insidious because a lot of rules have order dependent lists.
What I am thinking now is that buildozer should default to running buildifier in no-sort mode.

**Comment by laurentlb** [comment]
Why would you want to get an output that's not valid according to Buildifier?
We strongly recommend that every file in every repository to conform with Buildifier output. You should never have to see a file that's not correct. Many tools assume that the input is consistent with Buildifier.

**Comment by aiuto** [comment]
It is not about valid buildifier.
People are allowed to write rules that have list arguments where the order
matters, and sorting the lists would yield incorrect results.
As long as that is allowed and possible, then buildozer rewriting anything
outside the scope of a single edit is incorrect behavior.
Buildozer should edit semantics. Buildifier should format files. One tool,
one job.

**Comment by vladmos** [comment]
Even if we do that, `cc_embed_data.srcs` should be listed as no-sort anyway, right? Otherwise it'll be sorted by buildifier when it's called directly.

If we just disable the call to buildifier, buildozer can start spoiling files, e.g. `add_dep` will start adding dependencies to the end of a list, and maybe not in the canonical form.

Also, both tools are not able to output incorrectly formatted files (i.e. wrong indentation, missing commas, extra line breaks), so if the file is not correctly formatted it will be reformatted with the current implementation of buildifier anyway. The only difference we can make is whether to apply additional transformations (sort arguments, convert labels to the canonical form, etc.) or not. I'd say buildozer has to apply them to the rule it's currently editing, and it's much easier to apply them to the whole file than just to some statements, perhaps in some cases applying them not to the entire file doesn't make sense.

**Comment by aiuto** [comment]
Yes. Buildozer has to do what it needs to for target declarations that it
changes. It is only the reformatting of targets that are untouched that is
excessive behavior.

**Comment by laurentlb** [comment]
> cc_embed_data.srcs should be listed as no-sort

Do we really want it? I suspect most users want and expect the sorting. I think we've had the sorting enabled in google3 for years, did anything change?

Yes, it's not 100% safe, but sorting deps is also not safe. Users just put `# Do not sort` if they hit a corner case and they document it.

> It is only the reformatting of targets that are untouched that is excessive behavior.

I don't understand what you mean. By design, Buildifier always reformats the whole file.

**Comment by laurentlb** [comment]
Oops, sorry. I missed that difference.
It makes sense to align the behavior then.
