### ISSUE TITLE
Buildifier: support MODULE.bazel files

### ISSUE THREAD

**Issue by phst** [bazelbuild/buildtools#1031]
Bazel 5 has introduced module files (https://blog.bazel.build/2022/01/19/bazel-5.0.html, https://docs.bazel.build/versions/5.0.0/bzlmod.html). It would be great if Buildifier could support this new file type, e.g. using a `--type=module` flag.

**Comment by Wyverald** [comment]
In particular, it would be nice if `bazel_dep(name="foo", version="1.0")` kept being formatted on one line, instead of on multiple lines like a rule.

**Comment by vladmos** [comment]
I'll try to support module files by the next week.

If I understand it correctly, buildifier needs to

  1. Recognize module files by their names and apply the appropriate formatting rules (likely similar to BUILD files formatting)
  2. Find and format module files when it's called with `-r`
  3. Support a new file type in the linter (however I'm not going to add module-specific linter checks at the moment)
  4. For `bazel_dep` I'll make an exception similar to `package` in `BUILD` files so that it'll be allowed to format it as a one-liner.

**Comment by Wyverald** [comment]
Thank you, Vlad! That sounds perfect!
