### ISSUE TITLE
Return value in check mode is always zero

### ISSUE THREAD

**Issue by davido** [bazelbuild/buildtools#110]
The point of `check` mode is to be able to verify the formatting of `BUILD` files from the CI:

```
  $ buildifier -showlog -mode=check $(find . -name BUILD -o -name WORKSPACE -type f)
./WORKSPACE # reformat
  $ echo $?
0
```

I would expect different return code when formatting is wrong. That way I would not need to parse the program output.

**Comment by mwoehlke-kitware** [comment]
Huh, I was about to file the exact same issue. I would like to implement `buildifier -mode check` as a bazel test in our project. Unfortunately, because of this issue, I have to wrap it in a shell script to inspect the output. Yuck.

Please make `-mode=check` exit non-zero if the output is non-empty.
