### ISSUE TITLE
buildifier reformats macros after unrelated changes

### ISSUE THREAD

**Issue by pefoley2** [bazelbuild/buildtools#296]
I've got a bzl file with a macro of the form:

def rule_name(name, foo=True, **kwargs):

If I run buildifier on it once, I get this reformatted to:

def rule_name(name, foo = True, **kwargs):

If I then run buildifier on the file again without changing anything I get no modifications, as expected.

If I then modify a completely unrelated line further down in the file and re-run buildifier I get unexpected output of the form:

def rule_name(
           name,
           foo = True,
           **kwargs):

**Comment by vladmos** [comment]
It looks that the reason was that the second time you formatted the file in the build mode (`--type=build`, as opposed to the bzl mode, `--type=bzl`). For compatibility reasons the build mode is default if you provide a file via stdin.

In general function definitions are not allowed in BUILD files, but by design buildifier doesn't fail in such cases, instead it tries to format everything that's only supposed to be in bzl file as if it was launched in the bzl mode. Reason: the difference between BUILD and .bzl files is Bazel-specific, but Skylark can be used outside of Bazel.

Single-line lists with complex arguments are only allowed in the bzl mode, but in this example it should also be allowed in the build mode because this syntax is bzl-only.
