### ISSUE TITLE
.bzl formatter should preserve single-quoted strings when it would avoid backslash-escaping

### ISSUE THREAD

**Issue by cvrebert** [bazelbuild/buildtools#298]
One change that the formatter currently makes that I don't really agree with:
It changes single-quoted strings to double-quoted strings even in cases where it means adding backslashes, thus hindering readability.

* Example:
  * Old: `key_value_pairs = no_curly_braces.split('", "')`
  * New: `key_value_pairs = no_curly_braces.split("\", \"")`

Compare with the guidance in https://google.github.io/styleguide/pyguide.html#Strings that:
> It is okay to use the other quote character on a string to avoid the need to \ escape within the string.

**Comment by vladmos** [comment]
I'm in favor of the third option. If I as an author prefer using double quoted strings even if I need to escape all double-quote characters in it, then it should be my choice to do so.

The should be a similar rule for triple quoted strings: If at least one character needs to be escaped because of switching from `'''` to `"""`, then `'''` should be used.
