### ISSUE TITLE
buildifier on .bzl files messes up end of line comments

### ISSUE THREAD

**Issue by shahms** [bazelbuild/buildtools#301]
The end of line comment handling in .bzl files is pretty broken, take, for example:

```
def _flags(values, defaults):
  return [flag  # Example comment.
          for flag in [_flag(name, type(default), values.pop(name, default))
                       for name, default in defaults.items()]  # Clarififcation.
          if flag != None]  # Skip empty elements.
```

This is reformatted into the (frankly atrocious):

```
    return [flag for flag in [_flag(name, type(default), values.pop(name, default)) for name, default in defaults.items()] if flag != None]  # Exmaple.
# Clarification.
# Skip empty elements.
```

**Comment by laurentlb** [comment]
Formatting of comprehension looks broken. It might be the same bug as #302.

**Comment by vladmos** [comment]
The reason is: buildifier decides whether to use the multiline mode for comprehensions just comparing the positions of the opening brackets and the first expression (`flag` and `_flag(...)` in the example above). In both cases they are placed on the same line, that's why buildifier uses the single-line mode, and suffix comments that can't fit are just flushed after the line is ended.

The correct way to fix is to use the multiline mode if there's at least one line break before an if- or for-clause in the comprehension. Note that it's not equivalent to checking if the opening and closing brackets are located on different lines. For instance, the following example is formatted in the single-line mode although the opening and closing brackets are on different lines:

    flags = [f for f in _flags(
        foo,
        bar,
    ) if f]

This will be consistent with how buildifier chooses between single- and multiline modes for sequences like lists or tuples.
