### ISSUE TITLE
Released buildifier 0.15.0 checksum changed

### ISSUE THREAD

**Issue by scele** [bazelbuild/buildtools#383]
We had been pulling buildifier into our builds like this:
```py
http_file(
    name = "buildifier",
    urls = ["https://github.com/bazelbuild/buildtools/releases/download/0.15.0/buildifier"],
    sha256 = "0dea01a7a511797878f486e6ed8e549980c0710a0a116c8ee953d4e26de41515",
    executable = True,
)
```
About 7 hour ago, our CI broke due to checksum mismatch. The new checksum is 769b9757644a8ec9c4b07369fda4a3e6592639a1338a7a03225ceeedbc760b45.

Did you update the files in the 0.15.0 release? If yes, would you like to provide guarantees that releases are immutable in the future? If not, do you have any idea why the checksum could have changed?

Meanwhile, I guess I'll migrate to the approach of [building buildifier from sources](https://github.com/bazelbuild/buildtools/blob/master/buildifier/README.md#setup-and-usage-via-bazel) with the go toolchain...

**Comment by jwnimmer-tri** [comment]
This broke us as well.  The fix for #380 was suspiciously contemporaneous @pmbethe09.

**Comment by pmbethe09** [comment]
Yes, this was me -- I am sorry about that.  I hadn't realized that some were pulling in a release version with a sha256.  I guess if you are in an otherwise non-Go project it makes sense so you don't have to pull in the whole go_rules library just to build buildifier.

I will not change a release again like this, however I am not able to recover the previous version.
Instead I will cut a new binary release today, ensuring the -version works.

**Comment by pmbethe09** [comment]
FYI: https://github.com/bazelbuild/buildtools/releases/tag/0.17.2
