### ISSUE TITLE
Publish gh release binaries

### ISSUE THREAD

**Issue by softprops** [bazelbuild/buildtools#44]
I'd like my team to use this tool without forcing them all to install the go runtime

**Comment by pmbethe09** [comment]
When https://github.com/bazelbuild/buildifier/pull/45 lands, I will make a tag and a companion release

**Comment by softprops** [comment]
Sweet.

**Comment by pmbethe09** [comment]
I added Mac and linux64 builds -- hopefully that is enough?

**Comment by bolinfest** [comment]
Personally, I also need this on Windows.

**Comment by softprops** [comment]
Mac is perfect for me. Linux will be great for ci validation. Thanks @pmbethe09!

**Comment by pmbethe09** [comment]
I don't have a good way to make a Windows release -- let me ask the bazel team for suggestions

**Comment by softprops** [comment]
looks like the links for the OSX release bins are invalid here https://github.com/bazelbuild/buildifier/releases. is this the right place to look?

**Comment by pmbethe09** [comment]
Not sure how that happened, but I have fixed this.

**Comment by bolinfest** [comment]
@pmbethe09 The OSX release worked for me, but the Linux one claims that it does not support the `-tables` flag. Are you sure you built it from the correct commit?

**Comment by pmbethe09** [comment]
...  No not sure.  We need a better release process as these were ad-hoc.  
I have updated to fresh builds.

**Comment by bolinfest** [comment]
@pmbethe09 You might be able to have Circle-CI do the build and publish it for you. That's what we do for Nuclide, and the setup does not appear to be `npm`/`apm` specific: https://github.com/facebook/nuclide/blob/master/circle.yml. (Though maybe it is because somewhere we have to provide our credentials to publish on our behalf to `npm`...)

Also, FWIW, have you just been changing the binaries under the release tag rather than stamping out a new release with its own version number? It feels a little dodgy to just change the binaries in-place.

**Comment by pmbethe09** [comment]
Yes, but only because I didn't know what I was doing -- no more changes as of now :)

**Comment by bolinfest** [comment]
No worries: I'm sure 0.4.4 will go much smoother!

**Comment by pmbethe09** [comment]
closing as automation and Windows are covered in other issues
