### ISSUE TITLE
Provide a buildifier option for more tooling-friendly output

### ISSUE THREAD

**Issue by allevato** [bazelbuild/buildtools#477]
I've integrated buildifier linting/formatting into https://github.com/bazelbuild/vscode-bazel, and I think there are a couple enhancements that could be made to improve lint integration with IDEs:

**A more structured output mode.** Protos would be good here, similar to how I can run `bazel query --output=proto` and get an easily consumable binary proto stream back. Right now I take the text output and scrape it for line numbers, categories, and messages, but this is a little unclean because some messages can span multiple lines. (https://github.com/bazelbuild/vscode-bazel/blob/master/src/buildifier/buildifier.ts#L159-L180)

**Finer-grained location information about where lint warnings occur.** Right now a lint warning only indicates the line number of the issue. In VS Code, I register a diagnostic that occupies (and thus, underlines) the entire line (starting from the first non-whitespace character). It would be nice to get precise start and end line/column information for warnings so that I can highlight the exact issue. For example, if one of many bindings in a `load(...)` statement is unused, I would like to highlight just the one that should be removed.

**Comment by pmbethe09** [comment]
As to --output=proto mode seems like a good idea.  Is there a vs-code schema that would make sense to adopt?

**Comment by allevato** [comment]
The closest thing I can point to is the `vscode.Diagnostic` interface definition, and some of the related types above it: https://github.com/Microsoft/vscode/blob/8f7bd57/src/vs/vscode.d.ts#L4187-L4239.

In terms of what data would be valuable to have returned in a proto, I don't think we need to match up too much with specific IDEs as long as we provide enough information to reconstitute them as the IDE's type easily. For each diagnostic I think most IDEs would be fine with a repeated message that wrapped these up in fields:

* file path
* line/column of the beginning of the lint violation
* line/column of the end of the lint violation
* category ([these](https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md) strings)
* full message

Anything else you can think of?

**Comment by laurentlb** [comment]
We discussed a `--output` flag here too: https://github.com/bazelbuild/buildtools/pull/313#issuecomment-443814783

**Comment by laurentlb** [comment]
@philwo told me this would be useful for reporting issues in the CI as well.

**Comment by philwo** [comment]
I think looking at what existing tools use as their machine-readable output format would also be worthwhile, because it would allow people to instantly plug Buildifier as a lint tool into their existing CI or editor.

I came across the "checkstyle" output format which is an XML based format originally used by the [Checkstyle](http://checkstyle.sourceforge.net/) tool. From a quick look, it seems to be supported by [Buildkite](https://github.com/bugcrowd/test-summary-buildkite-plugin), [Teamcity](https://confluence.jetbrains.com/display/TCD18/XML+Report+Processing), [Jenkins](https://github.com/jenkinsci/warnings-ng-plugin) as input formats (they can read and show the results) and e.g. [TSLint](https://palantir.github.io/tslint/formatters/checkstyle/), [ESLint](https://eslint.org/docs/user-guide/formatters/#checkstyle) and some tools in the Java ecosystem.

I don't know if it's actually a good format or if there's a more modern one that has succeeded it, but the principle stands - if we go with an existing one, we can reuse existing clients :)

Regarding proto, I'm sceptical if it's a good format for this purpose, because it requires the client to pull in protobuf as a dependency, which many people will not want to do. JSON or XML might not be as cool, but at least people can parse them in almost any modern language out there by just relying on the standard library.

In the meantime, I found the existing Buildifier output to be well parseable with a regex, so that's what we're currently using in Bazel's CI: https://github.com/bazelbuild/continuous-integration/blob/master/buildifier/buildifier.py#L13

**Comment by allevato** [comment]
Did you mean to close this issue?

**Comment by philwo** [comment]
Huh, no, definitely not! Sorry, I must have clicked the wrong button. 😬

**Comment by allevato** [comment]
They put those buttons so close together 😄 

I'm definitely not opposed to supporting other formats like JSON or XML as well, but I would wager that proto format isn't that bad for end users either. Chances are if they're using buildifier then they're using Bazel for other integrations as well, and (at least in my experience) the proto-formatted output for queries is much more pleasant to work with than XML. With XML I have to create my own abstractions around the generic nodes, whereas importing protobuf

**Comment by allevato** [comment]
Yikes, and somehow I just mashed the keyboard/trackpad the wrong way to close the issue accidentally too 😰

**Comment by laurentlb** [comment]
For the record, gcc 9 is using JSON: https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Message-Formatting-Options.html#index-fdiagnostics-format

Something like this should work for us too.
