### ISSUE TITLE
exit status for -mode=diff

### ISSUE THREAD

**Issue by brown** [bazelbuild/buildtools#496]
Recently buildifier was changed so that "buildifier -mode=diff BUILD" exits with status 4
when BUILD needs reformatting.  I'm not sure this is the right.  I'm running buildifier to
determine the diffs that need to be applied to BUILD in order to make it properly formatted.
buildifier should just output the diffs and exit with status 0.

**Comment by vladmos** [comment]
Buildifier has been returning 4 in case the diff is not empty since April: https://github.com/bazelbuild/buildtools/pull/283 . The standard `diff` utility also returns a non-zero code if the files being compared are different, this allows users to assert that the files are equal and fail with a verbose output otherwise.

How do you run buildifier (manually or as a part of a CI script) and what will be different for you if it returned 0?

**Comment by brown** [comment]
I'm running buildifier in https://github.com/brown/bazel-mode to get a diff, then apply it to a BUILD file.
I can handle buildifier returning a non-zero exit code when there are diffs.  I just wanted to confirm that
the decision to exit with 4 was a deliberate one for the "-mode=diff" and not an accident.  Thanks!
