### ISSUE TITLE
Buildozer remove doesn't handle labels

### ISSUE THREAD

**Issue by laurynasl-wix** [bazelbuild/buildtools#532]
This is more of a question/clarification. In rules_scala for unused dependencies we attempt to emit `buildozer` command suggestion for removing unused dependencies. The problem is that we only know the canonical label of the target (e.g. `//foo:foo`) and the user might have a shortened version ('//foo') in their dependency list. As such, if we suggest ```buildozer 'remove deps //foo:foo'```, it will not remove the dependency as it is declared as `//foo` in the BUILD.bazel file. Is this the expected behaviour?

cc: @ittaiz

**Comment by pdoyle12** [comment]
I was asked to look at this because I'm fixing a plausibly-related shortened label name issue (#528).  Can you provide the actual BUILD rule and buildozer command that are not working (or some equivalent that you have verified doesn't work)?

I've validated that buildozer does correctly shorten "@unused_deps//:unused_deps" to "@unused_deps" when removing deps in my local testing, and finds and removes that dependency (i.e., I can't reproduce the problem with your example), so I suspect it could have something to do with your specific case.

**Comment by laurynasl-wix** [comment]
Thanks for checking this out. My bad, I was using an older version of buildozer. I've checked with 0.20 release and it handles this case properly. Closing as this is already supported

**Comment by pdoyle12** [comment]
No problem; thanks!
