### ISSUE TITLE
Format different for file vs stdin

### ISSUE THREAD

**Issue by keith** [bazelbuild/buildtools#568]
With a bzl file with this contents:

```python
def _foo_impl(ctx):
    pass

foo = rule(
    fragments = ["apple"],
    implementation = _foo_impl,
    attrs = {},
)
```

Then running this command:

```
buildifier foo.bzl
cat foo.bzl | buildifier > bar.bzl
diff foo.bzl bar.bzl
```

You end up with this diff:

```diff
--- foo.bzl     2019-03-02 17:12:52.038689963 -0800
+++ bar.bzl     2019-03-02 17:13:04.429933521 -0800
@@ -2,7 +2,7 @@
     pass

 foo = rule(
+    attrs = {},
     fragments = ["apple"],
     implementation = _foo_impl,
-    attrs = {},
 )
```

I installed buildifier with `go get` so the version is redacted, but I just updated so it should be 4bcdbd1064fcc48180fa30400e39f7a940fdb8f9

**Comment by vladmos** [comment]
That is intentional for compatibility, but eventually it should format string as bzl files because their format is more flexible.

Now that there's the "default" file type for generic Starlark files (not necessarily for Bazel), buildifier should mark parsed files that come to stdin as default, they are the same as bzl in terms of formatting but some bzl-specific lints won't be applied to them.

**Comment by keith** [comment]
Ah makes sense, thanks for the context, here's a PR to do that https://github.com/bazelbuild/buildtools/pull/569

**Comment by thomasvl** [comment]
Shouldn't the `-type` also come into play?  i.e. - no matter what you send to stdin, you really should use `-type` to indicate if you expect it to format a BUILD/bzl/WORKSPACE?

**Comment by keith** [comment]
If you pass type this does work as expected

**Comment by vladmos** [comment]
Correct, stdin should be treated as default Starlark file (unless `--type` is provided explicitly), files should be parsed based on their filename/extension (also unless `--type` is provided explicitly).
