### ISSUE TITLE
Removing non-optional macro list

### ISSUE THREAD

**Issue by keith** [bazelbuild/buildtools#615]
When I have a build rule like this:

```python
unit_test(
    name = "PluginsTests",
    deps = [
        "Plugins",
    ],
)
```

And run this buildozer command:

```sh
buildozer "remove deps Plugins" //Modules/Plugins:PluginsTests
```

I end up with this:

```python
unit_test(name = "PluginsTests")
```

The problem here is that this macro defines `deps` as non optional:

```python
def unit_test(name, deps, flaky = False, use_test_host = False):
```

So this becomes invalid. Should this type signature be consulted and result in leaving `deps = []` instead?

**Comment by vladmos** [comment]
The problem is that buildifier/buildozer parse and analyze single files and don't resolve dependencies. It can be quite complicated especially if a macro is defined in a third party package which needs to be downloaded first.

Perhaps it's easier and more predictable to use `remove` and `set_if_absent` (given that #616 is fixed).
