### ISSUE TITLE
set_if_absent to empty list

### ISSUE THREAD

**Issue by keith** [bazelbuild/buildtools#616]
If I have a rule like this:

```python
unit_test(name = "PluginsTests")
```

And I want to add an empty `deps` attribute (currently because of this issue https://github.com/bazelbuild/buildtools/issues/615 but I think this is relevant regardless)

It looks like `set_if_absent` doesn't support setting something to nothing, without warning.

If I run:

```sh
buildozer "set_if_absent deps" Modules/Plugins:PluginsTests
```

It does actually do what I want:

```python
unit_test(
    name = "PluginsTests",
    deps = [],
)
```

But it also warns with:

```
Too few arguments for command 'set_if_absent', expected at least 2.
```

And exits 0. Is this behavior expected or should it not warn in this case?

**Comment by vladmos** [comment]
It's actually a bug. The function that checks for correct amount of arguments should exit (and it doesn't for some reason), and the `set` method recognizes that the value should be a list and populates it with the remaining arguments (which results in an empty list).

If you run `buildozer "set foo" :target` it will just crash because `foo` (unrecognized name) should be set as ident.

I think `set` and `set_if_absent` should accept 1 argument and fail afterwards if the value is expected to be a single string or ident and there are not enough arguments.

**Comment by vladmos** [comment]
Alternatively the commands can set the value to `None` if it's not provided and not expected to be a list. Would that make sense?

**Comment by keith** [comment]
That sounds goodn
