### ISSUE TITLE
buildifier wrongly warns about positional arguments for variadic function

### ISSUE THREAD

**Issue by marcohu** [bazelbuild/buildtools#727]
Given this workspace content:

```python
load("@rules_antlr//antlr:repositories.bzl", "rules_antlr_dependencies")

rules_antlr_dependencies("4.7.2")
```
Running buildifier yields the following warning:

```
WORKSPACE:31: positional-args: All calls to rules or macros should pass arguments by keyword (arg_name=value) syntax. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#positional-args)
```

But the function looks like this:

```python
def rules_antlr_dependencies(*versions):
    """Loads the dependencies for the specified ANTLR releases.

    Args:
      *versions: the ANTLR releases to make available.
    """
    ...
```

Ideally, buildifier should analyze the actual function definition in order to differentiate positional args vs variadic args.

Also, if a function only has 1 argument, enforcing the keyword seems a bit overkill to me.

**Comment by vladmos** [comment]
Buildifier currently can't parse the function definition because it works on separate files (while analyzing a `WORKSPACE` file it doesn't have access to the `.bzl` file where the function is defined).

However perhaps it makes sense to relax the warning by not enforcing it on one argument functions.
