### ISSUE TITLE
Last release was about 2 months ago

### ISSUE THREAD

**Issue by swolchok** [bazelbuild/buildtools#73]
Could you please cut a new release?

**Comment by pmbethe09** [comment]
Sure.  We don't have an automated method for this yet.

**Comment by pmbethe09** [comment]
https://github.com/bazelbuild/buildtools/releases/tag/0.4.5

Will try to do this monthly.  May even try to automate

**Comment by jwnimmer-tri** [comment]
It seems like we're approaching ~6 months since the last release.  Is there any chance I could agitate for (and/or help with) a new release soonish?  There are lots of goodies in master, so I'm building from source, but it's slightly finicky to integrate and track buildtools's build-time dependencies.

Thanks in advance for any help or suggestions.

**Comment by pmbethe09** [comment]
Thanks for the nudge

https://github.com/bazelbuild/buildtools/releases/tag/0.6.0
