### ISSUE TITLE
File not found error with buildozer

### ISSUE THREAD

**Issue by rschiu** [bazelbuild/buildtools#731]
Latest commit (a795ddb) in buildozer is causing file not found error and blocking presubmit.  An example error can be seen in https://source.cloud.google.com/results/invocations/e09ece88-4c14-4d0b-92bd-eb5f122cbe09/targets.  Could you please take a look?  Thanks.

Running check buildozer fix... ++ run_buildozer
++ /tmpfs/src/tools/bin/buildozer -quiet 'fix movePackageToTop unusedLoads usePlusEqual' //...:__pkg__
/tmpfs/src/github/gapid/.../BUILD.bazel: file not found or not readable
++ local r=2
++ '[' 2 -eq 3 ']'
++ return 2
++ echo FAILED
FAILED
++ echo '  Error executing: run_buildozer'
  Error executing: run_buildozer
++ exit 1

**Comment by vladmos** [comment]
@aljoscha FYI

**Comment by aljoscha** [comment]
This is in fact caused by the change that I contributed. The reason is that `targetExpressionToBuildFiles` in `buildozer.go` relied on the fact that `InterpretLabelForWorkspaceLocation` returns a particularly formatted `buildFile` name for targets of the form `//...:some-rule`. For targets of this format the function returned `/path/to/workspace/.../BUILD`, which `targetExpressionToBuildFiles` understands and then cuts off the trailing `/.../BUILD` part to to the directory traversal.

A fix for this is to teach `targetExpressionToBuildFiles` to also understand the `BUILD.bazel` suffix, I show how to do this here: https://github.com/aljoscha/buildtools/commit/83e51f1a4c854bdedf3e05e35cde40b429efddba. I don't think that this is maintainable, though. That interaction between `InterpretLabelForWorkspaceLocation` and `targetExpressionToBuildFiles` seems a bit sketchy to me.

**Comment by aljoscha** [comment]
I have a better fix in https://github.com/bazelbuild/buildtools/pull/732. I'm a bit hesitant about this change because I don't know if this will break other things. We might be going down a rabbit hole with this. 😅

**Comment by hevrard** [comment]
Glad to see a fix being promptly prepared!
This issue makes all our presubmit test fail, so we can't really make progress, and a fix to this issue is rather urgent to us!
Thanks
