### ISSUE TITLE
Buildtoosl failing on Bazel CI after

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/buildtools#776]
https://buildkite.com/bazel/buildtools/builds/1506#ff9797a6-5276-4c54-8607-ccd2b8596ba8
```
(15:55:25) ERROR: An error occurred during the fetch of repository 'skylark_syntax':
   failed to fetch skylark_syntax: fetch_repo: unrecognized import path "go.starlark.net"
```

This only started happening from Monday, looks like it's caused by some infra change.

@jayconrod Do you have any idea about this error message?

/cc @vladmos

**Comment by jayconrod** [comment]
There are a few different problems in WORKSPACE. I'll work on PR.

* `io_bazel_rules_go` is out of date. The oldest supported branch is 0.20.x, but 0.16.3 is used here. There have been incompatible changes in Bazel since then, so old versions likely won't work.
* `bazel_gazelle` is out of date. `go_repository` comes from there, and a lot of improvements have been made since this commit.
* The `go_repository` rule for `skylark_syntax` refers to a commit that doesn't exist (maybe from a PR or branch that's been deleted?).
* The `importpath` for `skylark_syntax` is incorrect. That will break with newer versions.

**Comment by jayconrod** [comment]
(Ignore my previous comment, was looking at an old commit)

**Comment by vladmos** [comment]
I updated the WORKSPACE file a week ago and understand how it could break things in theory, but

  1. It worked well locally even after `bazel clean --expunge`
  2. All the tests on the CI also passed for that change
  3. Only Windows tests broke on the CI today (a scheduled nightly build passed successfully and only the tests for an unrelated change started to break).

**Comment by jayconrod** [comment]
I couldn't reproduce this on my Windows machine. The tests crash Bazel with `--enable_runfiles` because I don't have symbolic links enabled. Fetching that repo seems to work okay at the moment though.

The error message sounds like `fetch_repo` (a tool run inside `go_repository`) was not able to resolve `go.starlark.net` to a repository. Internally, it will fetch `https://go.starlark.net/?go-get=1`, then look for a `meta` tag that points it to the repo. It seems like that's being served correctly now, but maybe it went down earlier? That logic is not OS-specific, so I don't know why it would fail on Windows specifically.

Something to try instead:

```
go_repository(
    name = "skylark_syntax",
    importpath = "go.starlark.net",
    sum = "h1:4jRCa7xxEE+8+CDxrq64JNGsuui8/Y1/enYVey/vsjo=",
    version = "v0.0.0-20190717023158-fc7a7f44baed",
)
```

If `go_repository` is used with the `version` and `sum` attributes instead of `commit`, it will download a .zip file of the module from the Go module proxy. That should be faster and more reliable than cloning the repo.

**Comment by vladmos** [comment]
I managed to fix the problem on the CI by updating the commit hash for skylark_syntax to the latest (`6677ee5c7211380ec7e6a1b50dc45287e40ca9e1`): https://buildkite.com/bazel/buildtools/builds/1512

If you recommend to replace it with `version` and `sum` anyway, where can I get the correct values from?

**Comment by jayconrod** [comment]
I generated the rule above with:

`bazel run //:gazelle -- gazelle update-repos go.starlark.net@fc7a7f44baed`

If you omit the `@` and everything after that, it will use the latest version, or the latest commit if there is no version.

Internally, this runs `go mod download -json go.starlark.net`.

**Comment by vladmos** [comment]
Thanks!

**Comment by pcj** [comment]
Leaving a note and others here after searching for `fetch_repo: unrecognized import path "go.starlark.net"`.  I'm seeing this error in CI at the moment which is failing all builds.

Attempting to `curl -v https://go.starlark.net` yields 503 "backend is unhealthy"

GitHub status page shows that they are currently having an outage of github pages, so it appears that go.starlark.net is dependent upon a correctly functioning github pages.
